exclude: ^(poetry.lock|.idea/)
default_stages:
  - commit
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.31.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.256'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [ "--line-length", "100" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^LICENSE|\.(html|csv|txt|svg|py)$
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: https://github.com/fredrikaverpil/creosote.git
    rev: v2.4.0
    hooks:
      - id: creosote
        args: [
          "--venv=.venv",
          "--paths", "app.py", "config.py", "cvpartner", "profile",
          "--deps-file=pyproject.toml",
          "--sections=tool.poetry.dependencies",
          "--exclude-deps", "uvicorn",
        ]

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
#        exclude: (?x)(_test.py$)
        additional_dependencies:
          - types-python-dateutil==2.8.2
          - types-python-slugify==6.1.0
          - types-pytz==2022.1.1
          - types-requests==2.28.1
          - types-toml==0.10.2
